# Site settings
title: Xinyu Wang's Blog
email: xinyugrey@163.com
description: > # this means to ignore newlines until "baseurl:"
  I am ..................
baseurl: "/post" # the subpath of your site, e.g. /blog/
url: "https://xinyugrey.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  XinyuGrey

# Build settings
markdown: kramdown
